site_name: Fireactions
repo_name: "hostinger/fireactions"
repo_url: https://github.com/hostinger/fireactions
site_url: https://hostinger.github.io/fireactions/
edit_uri: edit/main/docs/

theme:
  name: material
  logo: logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
  palette:
    primary: red
  include_sidebar: true

nav:
  - Home:
      - Overview: "index.md"
  - Getting Started:
      - Intro: "getting-started/index.md"
      - Installing with Ansible: "getting-started/ansible-installation.md"
      - Installing manually: "getting-started/manual-installation.md"
      - Upgrading: "getting-started/upgrading.md"
  - User Guide:
      - Configuration: "user-guide/configuration.md"
      - Monitoring: "user-guide/monitoring.md"
  - API Guide: "api/index.md"
  - SDK Guide:
      - "SDK": "sdk/index.md"
  - Examples: "examples/index.md"
  - FAQ: "faq.md"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.magiclink
